logging:
  level:
    root: info
    org.apache: warn
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      
server:
  error:
    whitelabel:
      enabled: false

destination:
  path: /Users/senthil/Downloads